package com.vroff.domain.model.tmdb.series

import com.vroff.domain.model.BackdropImage
import com.vroff.domain.model.PosterImage
import com.vroff.domain.model.tmdb.common.BaseDetails
import com.vroff.domain.model.tmdb.common.Genre
import com.vroff.domain.model.tmdb.common.ProductionCompany
import com.vroff.domain.model.tmdb.common.ProductionCountry
import com.vroff.domain.model.tmdb.common.SpokenLanguage

data class SeriesDetail(
    override val adult: Boolean,
    override val backdropImage: BackdropImage?,
    override val createdBy: List<CreatedBy>,
    override val episodeRunTime: List<Long>,
    override val firstAirDate: String,
    override val genres: List<Genre>,
    override val homepage: String,
    override val id: Long,
    override val inProduction: Boolean,
    override val languages: List<String>,
    override val lastAirDate: String,
    override val lastEpisodeToAir: LastEpisodeToAir,
    val name: String,
    override val networks: List<Network>,
    override val numberOfEpisodes: Long,
    override val numberOfSeasons: Long,
    override val originCountry: List<String>,
    override val originalLanguage: String,
    override val originalName: String,
    override val overview: String,
    override val popularity: Double,
    override val posterImage: PosterImage?,
    override val productionCompanies: List<ProductionCompany>,
    override val productionCountries: List<ProductionCountry>,
    override val seasons: List<Season>,
    override val spokenLanguages: List<SpokenLanguage>,
    override val status: String,
    override val tagline: String,
    override val type: String,
    override val voteAverage: Double,
    override val voteCount: Long,
    val aggregateCredits: AggregateCredits,
) : BaseDetails(
        adult = adult,
        backdropImage = backdropImage,
        createdBy = createdBy,
        episodeRunTime = episodeRunTime,
        firstAirDate = firstAirDate,
        genres = genres,
        homepage = homepage,
        id = id,
        inProduction = inProduction,
        languages = languages,
        lastAirDate = lastAirDate,
        lastEpisodeToAir = lastEpisodeToAir,
        title = name,
        networks = networks,
        numberOfEpisodes = numberOfEpisodes,
        numberOfSeasons = numberOfSeasons,
        originCountry = originCountry,
        originalLanguage = originalLanguage,
        originalName = originalName,
        overview = overview,
        popularity = popularity,
        posterImage = posterImage,
        productionCompanies = productionCompanies,
        productionCountries = productionCountries,
        seasons = seasons,
        spokenLanguages = spokenLanguages,
        status = status,
        tagline = tagline,
        type = type,
        voteAverage = voteAverage,
        voteCount = voteCount,
        credits = aggregateCredits,
    )
